import { ActionForm } from "@/components/action-form";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader, MoneyDisplay } from "@koeki/ui";
import { getAgentDetail, getAssignableAgents, taskLabels } from "@/lib/team-service";
import { getReportExpectations } from "@/lib/report-service";
import { demoMode, hasPermission, requirePermission } from "@/lib/session";
import { addAgentNote, assignDossier, updateParticipation } from "../actions";

export default async function AgentDetail({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requirePermission("team:read"), { userId } = await params, query = await searchParams;
  const [data, expectations, agents] = await Promise.all([getAgentDetail(session, userId), getReportExpectations(session, userId), getAssignableAgents(session)]);
  if (!data) notFound();
  const date = (value: Date | null) => value ? value.toLocaleDateString("fr-FR", { timeZone: "Europe/Paris" }) : "Date inconnue";
  const activity = [...data.payments.map((payment) => ({ id: payment.id, label: `Paiement ${payment.receiptNumber}`, amount: payment.amount, status: payment.status, at: payment.validatedAt ?? payment.createdAt, known: Boolean(payment.validatedAt), href: `/ninjas/${payment.ninjaId}` })), ...data.transactions.map((transaction) => ({ id: transaction.id, label: `${transaction.type === "DONATION" ? "Don" : "Rachat"} ${transaction.receiptNumber}`, amount: transaction.totalAmount, status: transaction.status, at: transaction.validatedAt ?? transaction.createdAt, known: Boolean(transaction.validatedAt), href: `/ninjas/${transaction.ninjaId}` }))].sort((a, b) => +b.at - +a.at);
  const backQuery = query.retour && /^[\w%&=+.-]+$/.test(query.retour) ? `?${query.retour}` : "";
  return <div className="page-wrap"><PageHeader eyebrow="Fiche agent · encadrement" title={data.user.name} description={data.user.revokedAt ? "Compte désactivé ; les historiques métier sont conservés." : "Dossiers, participation et accompagnement de l’agent."} actions={<Link href={`/equipe${backQuery}`} className="button button-ghost">Retour à l’équipe</Link>} />
    {query.erreur && <p className="notice error" role="alert">{query.erreur}</p>}
    <section className="panel"><h2>Participation au service</h2>{data.user.participations.length ? data.user.participations.map((part) => <p key={part.id}>Entrée : {date(part.startsAt)} · observée le {date(part.observedAt)} · {part.endsAt ? `sortie le ${date(part.endsAt)}` : "participation ouverte"} · {part.rankingEligible ? "Participe au classement" : "Hors classement"} · source {part.dateSource === "DECLARED" ? "déclaration" : "observation, date initiale inconnue"}</p>) : <p>Aucune période de participation déclarée.</p>}<h3>Absences déclarées</h3>{data.user.absences.length ? data.user.absences.map((absence) => <p key={absence.id}>{date(absence.startsAt)} au {date(absence.endsAt)} · {absence.reason || "Sans motif détaillé"}</p>) : <p>Aucune absence déclarée.</p>}
      {hasPermission(session, "team:assign") && !demoMode && <details><summary>Déclarer une participation, une sortie ou une absence</summary><ActionForm action={updateParticipation} className="form-grid"><input type="hidden" name="userId" value={userId} /><label>Action<select name="intent"><option value="absence">Déclarer une absence</option><option value="join">Ouvrir une participation</option><option value="leave">Clore la participation aujourd’hui</option></select></label><label>Date d’entrée / début d’absence<input type="date" name="startsAt" /></label><label>Fin d’absence<input type="date" name="endsAt" /></label><label><input type="checkbox" name="rankingEligible" defaultChecked /> Participation explicite au classement lors de l’entrée</label><p>Une date d’entrée laissée vide reste inconnue. La participation au classement commence au plus tôt à son observation.</p><label>Justification<textarea name="reason" minLength={5} maxLength={1000} required /></label><button className="button button-primary">Enregistrer la déclaration</button></ActionForm></details>}
    </section>
    <section className="panel" id="dossiers"><h2>Dossiers attribués</h2>{data.dossiers.length ? data.dossiers.map((ninja) => <article key={ninja.id}><h3><Link href={`/ninjas/${ninja.id}`}>{ninja.firstName} {ninja.lastName}</Link></h3><p>{ninja.status === "ACTIVE" ? "Dossier actif" : ninja.status === "DECEASED" ? "Ninja décédé" : "Dossier archivé"}</p>{hasPermission(session, "team:assign") && !demoMode && <details><summary>Réaffecter ce dossier</summary><ActionForm action={assignDossier} className="form-grid"><input type="hidden" name="ninjaId" value={ninja.id} /><label>Nouveau référent<select name="assigneeId" defaultValue={userId}><option value="">À attribuer</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label><label>Justification<input name="reason" minLength={5} maxLength={1000} required /></label><button className="button button-primary">Réaffecter le dossier</button></ActionForm></details>}</article>) : <p>Aucun dossier attribué.</p>}<h3>Historique des affectations</h3>{data.assignments.map((assignment) => <p key={assignment.id}>{date(assignment.createdAt)} · {assignment.ninjaId ? "Dossier" : "Tâche"} · {assignment.assignedAgentId === userId ? "Attribué à cet agent" : "Réattribué ou mis en attente"} · {assignment.reason}</p>)}</section>
    <section className="panel"><h2>Tâches et rapports</h2><p><Link href={`/taches?agent=${userId}`}>Ouvrir les tâches de cet agent</Link> · <Link href={`/reports?auteur=${userId}`}>Ouvrir ses rapports accessibles</Link></p>{data.tasks.map((task) => <p key={task.id}>{task.title} · {taskLabels[task.status]} · {date(task.dueAt)}</p>)}<h3>Rapports attendus</h3><p>{expectations.configured ? "Cadence hebdomadaire configurée" : "Attente non configurée"}</p>{expectations.periods.map((period) => <p key={period.start}>{period.start} au {period.end} · {period.state} · échéance {date(period.dueAt)}</p>)}</section>
    <section className="panel" id="activite"><h2>Activité chronologique</h2><p>90 derniers jours, au maximum 50 paiements et 50 dons/rachats. Chaque ligne ouvre le dossier source autorisé. Les dates de création ne sont pas présentées comme des dates de validation.</p>{activity.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Opérations de cet agent"><table><thead><tr><th>Date</th><th>Opération</th><th>État</th><th>Montant</th></tr></thead><tbody>{activity.map((item) => <tr key={item.id}><td>{date(item.at)}{!item.known && <small> · création, validation inconnue</small>}</td><td><Link href={item.href}>{item.label}</Link></td><td>{{ VALIDATED: "Validé", REVERSED: "Inversé", CANCELLED: "Annulé", PENDING: "En attente", PENDING_APPROVAL: "À approuver", DRAFT: "Brouillon" }[item.status] ?? item.status}</td><td><MoneyDisplay amount={item.amount} /></td></tr>)}</tbody></table></div> : <p>Aucune opération enregistrée sur cette période.</p>}<h3>Évolution hebdomadaire publiée</h3>{data.weekly.length ? data.weekly.map((week) => <p key={week.weekKey}><Link href={`/classement?semaine=${week.weekKey}`}>{week.weekKey}</Link> · {week.operations === null ? "Hors population de cette semaine" : `${week.operations} opérations · rang ${week.rank}`} · version {week.version} · {week.coverageComplete ? "Couverture complète" : "Historique incomplet"}{week.correctionNeeded && " · correction à examiner"}</p>) : <p>Aucune semaine clôturée disponible. Aucune progression ne peut encore être calculée.</p>}<Link href="/classement">Ouvrir le classement collectif</Link></section>
    {hasPermission(session, "team:notes") && <section className="panel"><h2>Notes réservées à l’encadrement</h2><p>Ces notes ne sont jamais incluses dans les notifications ni dans le classement collectif.</p>{data.notes.map((note) => <article key={note.id}><p>{date(note.createdAt)} · auteur {note.authorName}</p><p style={{ whiteSpace: "pre-wrap" }}>{note.body}</p></article>)}{!demoMode && <ActionForm action={addAgentNote} className="form-grid"><input type="hidden" name="userId" value={userId} /><label>Nouvelle note<textarea name="body" minLength={5} maxLength={4000} required /></label><button className="button button-primary">Ajouter une note interne</button></ActionForm>}</section>}
  </div>;
}
