import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, ClipboardList, FileText } from "lucide-react";
import { EmptyState, MetricCard, MoneyDisplay, NinjaAvatar, PageHeader, SectionHeader, StatusBadge } from "@koeki/ui";
import { ActionForm } from "@/components/action-form";
import { ActivityChart } from "@/components/team-charts";
import { TeamPeriod } from "@/components/team-period";
import { getAgentDetail, taskLabels } from "@/lib/team-service";
import { getAgentAnalytics, resolveTeamPeriod } from "@/lib/team-analytics";
import { getHandledNinjas } from "@/lib/handled-ninjas";
import { getReportExpectations } from "@/lib/report-service";
import { demoMode, hasPermission, requirePermission } from "@/lib/session";
import { addAgentNote, updateParticipation } from "../actions";

export default async function AgentDetail({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requirePermission("team:read"), { userId } = await params, query = await searchParams;
  const view = ["dossiers", "activite", "accompagnement"].includes(query.vue ?? "") ? query.vue! : "apercu";
  let period, periodError;
  try { period = resolveTeamPeriod({ from: query.du, to: query.au }); }
  catch { period = resolveTeamPeriod(); periodError = "Période invalide : les 30 derniers jours sont affichés."; }
  const [data, analytics, expectations, handled] = await Promise.all([
    getAgentDetail(session, userId, period), getAgentAnalytics(session, userId, period),
    getReportExpectations(session, userId), getHandledNinjas(session, userId, period),
  ]);
  if (!data || !analytics || !analytics.agents[0]) notFound();
  const agent = analytics.agents[0];
  const date = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("fr-FR", { timeZone: "Europe/Paris" }) : "Date inconnue";
  const activity = [
    ...data.payments.map((payment) => ({ id: payment.id, label: `Paiement ${payment.receiptNumber}`, amount: payment.amount, status: payment.status, origin: payment.operationOrigin, at: payment.validatedAt ?? payment.createdAt, known: Boolean(payment.validatedAt), href: `/ninjas/${payment.ninjaId}` })),
    ...data.transactions.map((transaction) => ({ id: transaction.id, label: `${transaction.type === "DONATION" ? "Don" : "Rachat"} ${transaction.receiptNumber}`, amount: transaction.totalAmount, status: transaction.status, origin: transaction.operationOrigin, at: transaction.validatedAt ?? transaction.createdAt, known: Boolean(transaction.validatedAt), href: `/ninjas/${transaction.ninjaId}` })),
  ].sort((a, b) => +b.at - +a.at);
  const periodQuery = new URLSearchParams({ du: analytics.from, au: analytics.to });
  const url = `/equipe/${userId}`;
  const taxUrl = `/equipe/taxes?${periodQuery}&agent=${encodeURIComponent(userId)}`;
  const statusLabels: Record<string, string> = { VALIDATED: "Validé", REVERSED: "Inversé", CANCELLED: "Annulé", PENDING: "En attente", PENDING_APPROVAL: "À approuver", DRAFT: "Brouillon" };
  return <div className="page-wrap agent-detail-page">
    <Link href={`/equipe?${periodQuery}&vue=agents`} className="back-link"><ArrowLeft size={16} aria-hidden="true" />Retour à l’équipe</Link>
    <PageHeader eyebrow="Fiche agent · encadrement" title={data.user.name} description={`${agent.participation} · interventions libres sur le registre partagé`}
      actions={<><Link href={taxUrl} className="button button-primary">Voir ses taxes encaissées</Link><Link href={`/taches?agent=${userId}`} className="button button-ghost"><ClipboardList size={16} aria-hidden="true" />Voir ses tâches</Link></>} />
    <div className="agent-identity-strip"><NinjaAvatar name={agent.name} /><StatusBadge status={agent.state === "DISABLED" || agent.state === "LEFT" ? "draft" : agent.absentNow ? "warning" : "paid"}>{agent.stateLabel}</StatusBadge><span>{agent.entryDateKnown ? `Entrée déclarée le ${date(agent.participationStartsAt)}` : "Date d’entrée non renseignée"}</span><span>Dernière opération dans la période : {agent.lastActivity ? date(agent.lastActivity) : "aucune"}</span></div>
    {periodError && <p className="notice error" role="alert">{periodError}</p>}{query.erreur && <p className="notice error" role="alert">{query.erreur}</p>}
    <TeamPeriod from={analytics.from} to={analytics.to} action={url} view={view} />
    <nav className="view-tabs" aria-label="Rubriques de la fiche agent">{[["apercu", "Aperçu"], ["dossiers", "Dossiers"], ["activite", "Opérations"], ["accompagnement", "Accompagnement"]].map(([key, label]) => <Link key={key} href={`${url}?${periodQuery}&vue=${key}`} aria-current={view === key ? "page" : undefined}>{label}</Link>)}<Link href={taxUrl}>Taxes encaissées</Link></nav>
    {view === "apercu" && <>
      <section className="metric-grid" aria-label="Bilan de l’agent">
        <MetricCard label="Opérations validées" value={agent.total} detail={`${agent.payments} paiements · ${agent.donations} dons · ${agent.buybacks} rachats`} />
        <Link className="metric-link" href={taxUrl}><MetricCard label="Encaissements fiscaux" value={<MoneyDisplay amount={BigInt(agent.collected)} compact />} detail="Voir chaque reçu fiscal de cet agent" tone="good" /></Link>
        <Link className="metric-link" href={`${url}?${periodQuery}&vue=dossiers`}><MetricCard label="Ninjas concernés" value={handled.length} detail="Interventions de la période, sans exclusivité" /></Link>
        <Link className="metric-link" href={`/taches?agent=${userId}`}><MetricCard label="Tâches ouvertes" value={agent.tasksOpen} detail={`${agent.tasksOverdue} en retard · ${agent.tasksBlocked} bloquées`} tone={agent.tasksOverdue || agent.tasksBlocked ? "warn" : "neutral"} /></Link>
      </section>
      <section className="panel"><SectionHeader title="Activité de l’agent" description="Opérations métier validées pendant la période sélectionnée" action={<Link href={`${url}?${periodQuery}&vue=activite`} className="text-link">Voir les opérations sources <ArrowRight size={16} aria-hidden="true" /></Link>} /><ActivityChart days={analytics.daily} /></section>
      <div className="duo-grid agent-followup"><section className="panel"><SectionHeader title="Travail en cours" action={<Link className="text-link" href={`/taches?agent=${userId}`}>Toutes les tâches</Link>} /><ul className="compact-list">{data.tasks.filter((task) => ["TODO", "IN_PROGRESS", "BLOCKED"].includes(task.status)).slice(0, 5).map((task) => <li key={task.id}><Link href={`/taches?id=${task.id}`}><strong>{task.title}</strong><span>{taskLabels[task.status]} · {task.dueAt ? date(task.dueAt) : "Sans échéance"}</span></Link></li>)}</ul>{agent.tasksOpen === 0 && <p className="empty-inline">Aucune tâche ouverte.</p>}<p className="muted">{agent.tasksDone} tâches terminées sur la période.</p></section>
        <section className="panel"><SectionHeader title="Rapports & suivi" action={<Link className="text-link" href={`/reports?auteur=${userId}`}>Ses rapports</Link>} /><div className="report-kpis"><span><strong>{agent.reportsSubmitted}</strong>soumis, en attente</span><span><strong>{agent.reportsApproved}</strong>approuvés</span></div><p>Soumissions et décisions datées dans la période.</p><details><summary>Rapports attendus</summary><p>{expectations.configured ? "Cadence hebdomadaire configurée" : "Attente non configurée"}</p>{expectations.periods.map((item) => <p key={item.start}>{item.reportId ? <Link href={`/reports/${item.reportId}`}>{item.start} au {item.end}</Link> : `${item.start} au ${item.end}`} · {item.state} · échéance {date(item.dueAt)}</p>)}</details></section>
      </div>
      <details className="methodology"><summary>Historique des classements publiés</summary>{data.weekly.length ? <ul className="compact-list">{data.weekly.map((week) => <li key={week.weekKey}><Link href={`/classement?semaine=${week.weekKey}`}><strong>{week.weekKey}</strong><span>{week.operations === null ? "Hors population" : `${week.operations} opérations · rang ${week.rank}`} · version {week.version} · {week.coverageComplete ? "Couverture complète" : "Historique incomplet"}{week.correctionNeeded && " · correction à examiner"}</span></Link></li>)}</ul> : <p>Aucune semaine clôturée disponible.</p>}</details>
    </>}
    {view === "dossiers" && <section className="panel" id="dossiers"><SectionHeader title="Ninjas concernés par ses opérations" description="Liste déduite des paiements, dons et rachats validés dans la période. Ces dossiers restent ouverts à tous les agents." />
      {handled.length ? <div className="assignment-list">{handled.map((ninja) => <details className="assignment-item" key={ninja.id}><summary><NinjaAvatar name={`${ninja.firstName} ${ninja.lastName}`} /><strong>{ninja.firstName} {ninja.lastName}</strong><span>{ninja.status === "ACTIVE" ? "Actif" : ninja.status === "DECEASED" ? "Décédé" : "Archivé"}</span></summary><div className="assignment-body"><Link href={`/ninjas/${ninja.id}`} className="text-link">Ouvrir le dossier ninja <ArrowRight size={16} aria-hidden="true" /></Link><p className="field-help">Le suivi ne réserve pas ce ninja à cet agent.</p></div></details>)}</div> : <EmptyState title="Aucun ninja concerné sur cette période" description="Une opération enregistrée par cet agent apparaîtra ici, quel que soit le ninja." />}
    </section>}
    {view === "activite" && <section className="panel" id="activite"><SectionHeader title="Journal des opérations" description="50 paiements et 50 dons/rachats maximum, sur la période sélectionnée" /><p>Tous les états et origines sont conservés. <Link href={taxUrl} className="text-link">Consulter l’ensemble des reçus fiscaux avec pagination</Link>.</p>
      {activity.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Opérations de cet agent"><table><thead><tr><th>Date</th><th>Opération</th><th>État / origine</th><th className="num">Montant</th></tr></thead><tbody>{activity.map((item) => <tr key={item.id}><td>{date(item.at)}{!item.known && <small className="cell-detail">Création · validation inconnue</small>}</td><td><Link href={item.href} className="text-link">{item.label}</Link></td><td><StatusBadge status={item.status === "VALIDATED" ? "paid" : "draft"}>{statusLabels[item.status] ?? item.status}</StatusBadge><small className="cell-detail">{item.origin === "BUSINESS" ? "Métier" : item.origin === "SELF_DECLARED" ? "Déclaration ninja" : "Historique ou technique"}</small></td><td className="num"><MoneyDisplay amount={item.amount} /></td></tr>)}</tbody></table></div> : <EmptyState title="Aucune opération sur cette période" description="Modifiez la période pour consulter un autre intervalle." />}
    </section>}
    {view === "accompagnement" && <div className="duo-grid"><section className="panel"><SectionHeader title="Participation & absences" description="Historique déclaré du service" /><div className="panel-body"><h3>Participation</h3>{data.user.participations.length ? data.user.participations.map((part) => <p key={part.id}>{date(part.startsAt)} → {part.endsAt ? date(part.endsAt) : "en cours"}<small className="cell-detail">{part.rankingEligible ? "Participe au classement" : "Hors classement"} · {part.dateSource === "DECLARED" ? "Déclaration" : `Observation le ${date(part.observedAt)}, entrée inconnue`}</small></p>) : <p>Aucune période déclarée.</p>}<h3>Absences déclarées</h3>{data.user.absences.length ? data.user.absences.map((absence) => <p key={absence.id}>{date(absence.startsAt)} → {date(absence.endsAt)}<small className="cell-detail">{absence.reason || "Sans motif détaillé"}</small></p>) : <p>Aucune absence déclarée.</p>}</div>
      {hasPermission(session, "team:assign") && !demoMode && <details><summary>Déclarer une participation ou une absence</summary><ActionForm action={updateParticipation} className="form-grid"><input type="hidden" name="returnTo" value={`${url}?${periodQuery}&vue=accompagnement`} /><input type="hidden" name="userId" value={userId} /><label>Action<select name="intent"><option value="absence">Déclarer une absence</option><option value="join">Ouvrir une participation</option><option value="leave">Clore la participation aujourd’hui</option></select></label><label>Date d’entrée / début d’absence<input type="date" name="startsAt" /></label><label>Fin d’absence<input type="date" name="endsAt" /></label><label className="checkbox-label"><input type="checkbox" name="rankingEligible" defaultChecked />Participation au classement lors de l’entrée</label><p className="field-help">Une date d’entrée laissée vide reste inconnue. L’éligibilité commence au plus tôt à son observation.</p><label>Justification<textarea name="reason" minLength={5} maxLength={1000} required /></label><button className="button button-primary">Enregistrer la déclaration</button></ActionForm></details>}
      </section>{hasPermission(session, "team:notes") && <section className="panel internal-notes"><SectionHeader title="Notes d’encadrement" description="Confidentielles · accessibles uniquement aux responsables" />{data.notes.length ? <ul className="note-list">{data.notes.map((note) => <li key={note.id}><span><FileText size={15} aria-hidden="true" />{note.authorName} · {date(note.createdAt)}</span><p>{note.body}</p></li>)}</ul> : <p className="empty-inline">Aucune note enregistrée.</p>}{!demoMode && <ActionForm action={addAgentNote} className="form-grid"><input type="hidden" name="returnTo" value={`${url}?${periodQuery}&vue=accompagnement`} /><input type="hidden" name="userId" value={userId} /><label>Nouvelle note<textarea name="body" minLength={5} maxLength={4000} required /></label><button className="button button-primary">Ajouter une note interne</button></ActionForm>}</section>}
    </div>}
  </div>;
}
