import Link from "next/link";
import { EmptyState, MoneyDisplay, PageHeader, SectionHeader } from "@koeki/ui";
import { getWeeklyRanking } from "@/lib/ranking-service";
import { closeRanking } from "./actions";
import { RankingSubmitButton } from "./submit-button";

const date = (value: Date | string) => new Date(value).toLocaleString("fr-FR", { timeZone: "Europe/Paris", dateStyle: "medium", timeStyle: "short" });
const kindLabel = { PAYMENT: "Paiement fiscal", DONATION: "Don", BUYBACK: "Rachat" };

export default async function RankingPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const data = await getWeeklyRanking(typeof params.semaine === "string" ? params.semaine : undefined, typeof params.version === "string" ? Number(params.version) : undefined);
  const query = typeof params.q === "string" ? params.q.trim().toLocaleLowerCase("fr") : "";
  const rows = data.manager && query ? data.rows.filter((row) => row.name.toLocaleLowerCase("fr").includes(query)) : data.rows;
  return <div className="page-wrap">
    <PageHeader eyebrow="Activité du service" title="Classement hebdomadaire" description="Une opération métier validée = une contribution. Aucun versement ni point de fidélité n’est attribué par ce classement." />
    <nav className="page-actions" aria-label="Choisir une semaine"><Link className="button button-ghost" href={`/classement?semaine=${data.previousKey}`}>← Semaine précédente</Link><Link className="button button-ghost" href="/classement">Semaine courante</Link>{data.week.key !== data.currentKey && <Link className="button button-ghost" href={`/classement?semaine=${data.nextKey}`}>Semaine suivante →</Link>}</nav>
    {typeof params.erreur === "string" && <p className="notice notice-error" role="alert">{params.erreur}</p>}
    {params.succes && <p className="notice" role="status">Le classement a été vérifié. Sa version publiée est indiquée ci-dessous.</p>}
    <section className="panel"><SectionHeader title={`${data.week.key} · ${data.closed ? `Version ${data.version}` : "Provisoire"}`} description={`Du ${date(data.week.startsAt)} inclus au ${date(data.week.endsAt)} exclu · Europe/Paris`} />
      <div className="panel-body"><p>{data.coverageComplete ? "Période couverte par des preuves de première validation." : "Historique incomplet : ce résultat ne constitue pas un classement officiel complet. Les dates et participations inconnues ne sont pas inventées."}</p>
        <p>Calculé le {date(data.calculatedAt)}. Formule V1 : paiements + dons + rachats validés et distincts. Montants informatifs, sans pondération.</p>
        {data.excludedUnknown > 0 && <p>{data.excludedUnknown} opération(s) avec une preuve historique insuffisante, exclue(s).</p>}
        {data.correctionNeeded && <p role="status" className="notice">Une opération ou une participation a changé depuis la clôture. La version publiée est conservée ; une correction motivée est nécessaire.</p>}
        {data.own ? <p><strong>Ma position : {data.own.rank}{data.own.rank === 1 ? "er" : "e"}</strong> · {data.own.operations ? `${data.own.operations} contribution(s)` : "Aucune opération"} · {data.own.comparison === null ? "Pas de comparaison" : `Évolution : ${data.own.comparison > 0 ? "+" : ""}${data.own.comparison} place(s)`}</p> : <p>Aucune participation au classement n’est enregistrée pour votre compte sur cette période.</p>}
      </div>
      {data.manager && <form className="filter-bar" method="get"><input type="hidden" name="semaine" value={data.week.key} /><label>Identité RP <input name="q" defaultValue={query} placeholder="Rechercher un agent" /></label><button className="button button-secondary" type="submit">Filtrer</button></form>}
      {rows.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Classement des agents"><table><thead><tr><th>Rang</th><th>Identité RP</th><th className="num">Opérations</th><th className="num">Paiements</th><th className="num">Dons</th><th className="num">Rachats</th><th className="num">Encaissé</th><th>Comparaison</th></tr></thead><tbody>{rows.map((row) => <tr key={row.userId}><td>{row.rank}</td><th scope="row">{data.manager ? <Link href={`/equipe/${row.userId}`}>{row.name}</Link> : row.name}</th><td className="num">{row.operations || "Aucune opération"}</td><td className="num">{row.payments}</td><td className="num">{row.donations}</td><td className="num">{row.buybacks}</td><td className="num"><MoneyDisplay amount={BigInt(row.collected)} /></td><td>{row.comparison === null ? "Pas de comparaison" : row.comparison === 0 ? "Position stable" : `${row.comparison > 0 ? "+" : ""}${row.comparison} place(s)`}</td></tr>)}</tbody></table></div> : <EmptyState title={data.demo ? "Démonstration : aucune donnée de classement" : "Aucun agent sur cette période"} description="Les responsables renseignent les périodes de participation depuis l’espace Équipe. Une absence d’activité ne signifie pas une faute." />}
    </section>
    <section className="panel"><SectionHeader title={data.manager ? "Contributions vérifiables de l’équipe" : "Mes contributions vérifiables"} description="Les opérations de collègues ne sont détaillées qu’aux responsables." />{data.sources.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Contributions vérifiables"><table><thead><tr><th>Type</th><th>Référence métier</th><th>Première validation</th><th className="num">Montant</th></tr></thead><tbody>{data.sources.map((source) => <tr key={`${source.kind}:${source.id}`}><td>{kindLabel[source.kind]}</td><td><Link href={`/classement/contributions/${source.kind}/${source.id}`}>{source.id}</Link></td><td>{date(source.validatedAt)}</td><td className="num"><MoneyDisplay amount={BigInt(source.amount)} /></td></tr>)}</tbody></table></div> : <p className="panel-body">Aucune contribution éligible.</p>}</section>
    <section className="panel"><SectionHeader title="Comprendre le classement" /><div className="panel-body"><p>Les brouillons, attentes, imports, écritures techniques et opérations annulées ou inversées sont exclus. Un don et son entrée en stock ne comptent qu’une fois. L’auteur d’origine reçoit la contribution, jamais le simple approbateur.</p><p>Les ex æquo partagent leur rang (1, 1, 3). La comparaison exige deux semaines clôturées et complètes, la même population et une participation couvrant les deux semaines. Les comptages et stocks restent des indicateurs séparés dans les statistiques.</p><p>Les comptes techniques ne participent pas automatiquement. Une sortie du service ne supprime pas les contributions des semaines précédentes.</p></div></section>
    {data.versions.length > 0 && <section className="panel"><SectionHeader title="Versions conservées" /><div className="panel-body">{data.versions.map((v) => <p key={v.version}><Link href={`/classement?semaine=${data.week.key}&version=${v.version}`}>Version {v.version}</Link> · {date(v.createdAt)}{"reason" in v && v.reason ? ` · ${v.reason}` : ""}</p>)}</div></section>}
    {data.manager && data.week.endsAt <= new Date() && <section className="panel"><SectionHeader title={data.closed ? "Publier une correction" : "Clôturer la semaine"} description="Les versions précédentes sont conservées. Une semaine ouverte ne peut jamais être clôturée." /><form action={closeRanking} className="panel-body"><input type="hidden" name="week" value={data.week.key} /><input type="hidden" name="version" value={data.latestVersion ?? ""} />{data.closed && <label>Motif de correction<textarea name="reason" required minLength={10} maxLength={2000} /></label>}<RankingSubmitButton correction={data.closed} disabled={data.demo || (data.closed && !data.correctionNeeded)} /></form></section>}
  </div>;
}
