import { ActionForm } from "@/components/action-form";
import Link from "next/link";
import { PageHeader, EmptyState } from "@koeki/ui";
import { getAssignableAgents, getTasks, priorityLabels, taskLabels } from "@/lib/team-service";
import { demoMode, hasPermission, requirePermission } from "@/lib/session";
import { formatReportDate } from "@/lib/report-period";
import { createTask, transitionTask, updateTaskAssignment } from "./actions";

export default async function TasksPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requirePermission("tasks:read"), query = await searchParams;
  const manager = hasPermission(session, "tasks:manage");
  const [data, agents] = await Promise.all([getTasks(session, { id: query.id, status: query.statut, page: Number(query.page) || 1, assignee: query.agent }), manager ? getAssignableAgents(session) : []]);
  const choices = <><option value="">À attribuer</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</>;
  const dates = (date: Date | null) => date ? date.toLocaleDateString("fr-FR", { timeZone: "Europe/Paris" }) : "Sans échéance";
  return <div className="page-wrap"><PageHeader eyebrow="Travail quotidien" title={manager ? "Tâches de l’équipe" : "Mes tâches"} description="Les objectifs et échéances sont fixés par l’encadrement. Indiquez votre avancement, vos blocages et la résolution." />
    {query.erreur && <p role="alert" className="notice error">{query.erreur}</p>}
    <section className="panel"><form method="get" className="filter-bar"><label>État<select name="statut" defaultValue={query.statut ?? ""}><option value="">Tous</option><option value="overdue">Échéance dépassée</option>{Object.entries(taskLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{manager && <label>Agent<select name="agent" defaultValue={query.agent ?? ""}><option value="">Toute l’équipe</option><option value="unassigned">À attribuer</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label>}<button className="button button-primary">Filtrer les tâches</button></form></section>
    {manager && !demoMode && <section className="panel"><details open={Boolean(query.reportId)}><summary>Créer une tâche de suivi</summary><ActionForm action={createTask} className="form-grid"><label>Titre<input name="title" required minLength={3} maxLength={160} /></label><label>Objectif et description<textarea name="description" required minLength={5} maxLength={4000} /></label><label>Agent<select name="assigneeId">{choices}</select></label><label>Priorité<select name="priority" defaultValue="NORMAL">{Object.entries(priorityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Échéance<input type="date" name="dueAt" /></label><label>Dossier ninja (identifiant facultatif)<input name="ninjaId" /></label><input type="hidden" name="reportId" value={query.reportId ?? ""} />{query.reportId && <p>Cette action sera liée au <Link href={`/reports/${query.reportId}`}>rapport source</Link>.</p>}<button className="button button-primary">Créer la tâche</button></ActionForm></details></section>}
    {data.tasks.length === 0 && <EmptyState title="Aucune tâche" description="Aucune tâche accessible ne correspond à cette sélection." />}
    {data.tasks.map((task) => <section className="panel" id={task.id} key={task.id}><h2>{task.title}</h2><p><strong>{taskLabels[task.status]}</strong> · Priorité {priorityLabels[task.priority]} · {task.assigneeName} · {dates(task.dueAt)}</p><p style={{ whiteSpace: "pre-wrap" }}>{task.description}</p>{task.resolution && <p>Résolution : {task.resolution}</p>}<p>{task.ninjaId && <Link href={`/ninjas/${task.ninjaId}`}>Dossier ninja</Link>} {task.reportId && <Link href={`/reports/${task.reportId}`}>Rapport source</Link>}</p>
      {!demoMode && (manager || !["DONE", "CANCELLED"].includes(task.status)) && <ActionForm action={transitionTask} className="form-grid"><input type="hidden" name="taskId" value={task.id} /><input type="hidden" name="version" value={task.version} /><label>Nouvel état<select name="status" defaultValue={task.status}>{Object.entries(taskLabels).filter(([key]) => manager || key !== "CANCELLED").map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Avancement, blocage ou résolution<textarea name="reason" maxLength={4000} /></label><button className="button button-primary">Mettre à jour l’avancement</button></ActionForm>}
      {manager && !demoMode && <details><summary>Réaffecter, prioriser ou modifier l’échéance</summary><ActionForm action={updateTaskAssignment} className="form-grid"><input type="hidden" name="taskId" value={task.id} /><input type="hidden" name="version" value={task.version} /><label>Agent<select name="assigneeId" defaultValue={task.assigneeId ?? ""}>{choices}</select></label><label>Priorité<select name="priority" defaultValue={task.priority}>{Object.entries(priorityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Échéance<input name="dueAt" type="date" defaultValue={task.dueAt ? formatReportDate(task.dueAt) : ""} /></label><label>Justification<textarea name="reason" minLength={5} maxLength={1000} required /></label><button className="button button-primary">Appliquer les changements</button></ActionForm></details>}
      <details><summary>Historique des transitions</summary>{task.transitions.map((transition) => <p key={transition.id}>{transition.createdAt.toLocaleString("fr-FR")} · {transition.fromStatus ? taskLabels[transition.fromStatus] : "Création"} → {taskLabels[transition.toStatus]} · {transition.reason || "Sans commentaire"}</p>)}</details>
    </section>)}
    <footer className="table-footer"><span>Page {data.page} sur {data.pageCount} · {data.total} tâches</span>{data.page > 1 && <Link href={`?${new URLSearchParams({ ...(query.statut ? { statut: query.statut } : {}), ...(query.agent ? { agent: query.agent } : {}), page: String(data.page - 1) })}`}>Précédent</Link>}{data.page < data.pageCount && <Link href={`?${new URLSearchParams({ ...(query.statut ? { statut: query.statut } : {}), ...(query.agent ? { agent: query.agent } : {}), page: String(data.page + 1) })}`}>Suivant</Link>}</footer>
  </div>;
}
