import { ActionForm } from "@/components/action-form";
import Link from "next/link";
import { prisma } from "@koeki/database";
import { PageHeader, MoneyDisplay, EmptyState } from "@koeki/ui";
import { getAssignableAgents, getTeamOverview } from "@/lib/team-service";
import { demoMode, hasPermission, requirePermission } from "@/lib/session";
import { assignDossier } from "./actions";

export default async function TeamPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requirePermission("team:read"), query = await searchParams;
  let data;
  try { data = await getTeamOverview(session, { from: query.du, to: query.au, search: query.q, status: query.etat, sort: query.tri, page: Number(query.page) || 1 }); }
  catch { data = await getTeamOverview(session); query.erreur = "Période invalide : affichage des sept derniers jours."; }
  const canAssign = hasPermission(session, "team:assign");
  const [agents, unassigned] = await Promise.all([canAssign ? getAssignableAgents(session) : [], !demoMode ? prisma.ninjaProfile.findMany({ where: { referenceAgentId: null, status: "ACTIVE" }, select: { id: true, firstName: true, lastName: true }, take: 30, orderBy: { lastName: "asc" } }) : []]);
  const filterQuery = new URLSearchParams({ du: data.from, au: data.to, ...(query.q ? { q: query.q } : {}), ...(query.etat ? { etat: query.etat } : {}), ...(query.tri ? { tri: query.tri } : {}) });
  return <div className="page-wrap"><PageHeader eyebrow="Pilotage responsable" title="Équipe" description="Participation déclarée, dossiers et opérations métier. L’absence d’activité enregistrée n’est pas un jugement sur le travail." actions={<Link className="button button-primary" href="/taches">Tâches de l’équipe</Link>} />
    {query.erreur && <p className="notice error" role="alert">{query.erreur}</p>}<section className="panel"><p><Link href="/reports?statut=SUBMITTED">{data.awaiting} rapports à examiner</Link> · <a href="#sans-referent">{data.unassigned} dossiers sans référent</a> · <Link href="/taches?statut=overdue">Consulter les tâches en retard</Link></p><form method="get" className="filter-bar"><label>Identité RP<input name="q" defaultValue={query.q} /></label><label>Du<input name="du" type="date" defaultValue={data.from} /></label><label>Au<input name="au" type="date" defaultValue={data.to} /></label><label>État<select name="etat" defaultValue={query.etat ?? ""}><option value="">Tous</option><option value="active">Participation active</option><option value="disabled">Comptes désactivés</option></select></label><label>Tri<select name="tri" defaultValue={query.tri ?? "name"}><option value="name">Identité A → Z</option><option value="name-desc">Identité Z → A</option></select></label><button className="button button-primary">Appliquer les filtres</button></form></section>
    <section className="panel"><h2>Suivi par agent</h2><p>Opérations validées datées dans la période choisie ; montants exacts en Ryō. Les dates de validation inconnues ne sont pas inventées. Dossiers et retards décrivent la situation actuelle. Rapports : périodes qui chevauchent la sélection, hors brouillons privés.</p>{data.rows.length ? <div className="table-scroll" tabIndex={0} role="region" aria-label="Suivi des agents"><table><thead><tr><th>Agent / participation</th><th>Dossiers</th><th>Paiements</th><th>Encaissements</th><th>Dons / rachats</th><th>Rapports reçus / attendus</th><th>Tâches en retard</th><th>Dernière opération</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id}><td><Link href={`/equipe/${row.id}?retour=${encodeURIComponent(filterQuery.toString())}`}>{row.name}</Link><br /><small>{row.state}{!row.entryKnown && " · entrée inconnue"}</small></td><td><Link href={`/equipe/${row.id}#dossiers`}>{row.dossiers}</Link></td><td><Link href={`/equipe/${row.id}#activite`}>{row.payments}</Link></td><td><MoneyDisplay amount={row.collected} /></td><td>{row.donations} / {row.buybacks}</td><td><Link href={`/reports?auteur=${row.id}`}>{row.reports}</Link> / {row.expectedReports ?? "Attente non configurée"}</td><td><Link href={`/taches?agent=${row.id}&statut=overdue`}>{row.overdue}</Link></td><td>{row.lastActivity?.toLocaleDateString("fr-FR") ?? "Aucune opération"}</td></tr>)}</tbody></table></div> : <EmptyState title="Aucun agent dans cette sélection" description="Les agents sans opération apparaissent également dans le registre." />}
      <footer className="table-footer"><span>{data.total} agents · page {data.page} sur {data.pageCount}</span>{data.page > 1 && <Link href={`?${filterQuery}&page=${data.page - 1}`}>Précédent</Link>}{data.page < data.pageCount && <Link href={`?${filterQuery}&page=${data.page + 1}`}>Suivant</Link>}</footer></section>
    <section className="panel" id="sans-referent"><h2>Dossiers à attribuer</h2><p>{data.unassigned} dossiers actifs sans référent · 30 premiers affichés.</p>{unassigned.map((ninja) => <details key={ninja.id}><summary>{ninja.firstName} {ninja.lastName} · Attribuer un référent</summary><p><Link href={`/ninjas/${ninja.id}`}>Ouvrir le dossier</Link></p>{canAssign && <ActionForm action={assignDossier} className="form-grid"><input type="hidden" name="ninjaId" value={ninja.id} /><label>Référent<select name="assigneeId" required><option value="">Choisir un agent</option>{agents.map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label><label>Motif<input name="reason" required minLength={5} maxLength={1000} /></label><button className="button button-primary">Attribuer le dossier</button></ActionForm>}</details>)}</section>
  </div>;
}
